apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: yapp-container
      image: nginx
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: app-cm
