apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-test
      image: nginx
      imagePullPolicy: Never
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-other-secret
              key: user