apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    imagePullPolicy: Never
    envFrom:
    - secretRef:
        name: my-secret
